version: '3'
services:
  postgres:
    container_name: container-postgresdb-cip
    image: postgres:10
    ports:
      - "5300:5432"
    environment:
      POSTGRES_USER: cip
      POSTGRES_PASSWORD: cip
      POSTGRES_DB: cip
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always

volumes:
  postgres-data: